### PR TITLE
Comment shows data context

### PR DESCRIPTION
**Pull request by knl-le**
At any data line a comment is added shows containing data as ascii chars

Closes: #4

### CODE REVIEW

**Review by AntumDeluge — CHANGES_REQUESTED** [review]
This is excellent! But I'd like to have a command line switch to disable it.

**Comment by knl-le** [comment]
I added command line parameter
output: to set output file name
hname: to set the c identifier name
nbdata: to set number of data each line
datacontent: to activate data content comment al each line

@AntumDeluge If you know better names for the parameter, please feel free to make suggestions. They will be very welcome.

**Comment by AntumDeluge** [comment]
@knl-le I'm getting a couple errors now when I try to build:

```
C:/Users/antum/Development/bin2header/source/src/bin2header.cpp: In function 'int main(int, char**)':
C:/Users/antum/Development/bin2header/source/src/bin2header.cpp:124:3: error: 'setNumberDataPerLine' was not declared in this scope
  124 |   setNumberDataPerLine(args["nbdata"].as<unsigned int>());
      |   ^~~~~~~~~~~~~~~~~~~~
C:/Users/antum/Development/bin2header/source/src/bin2header.cpp:129:3: error: 'setShowDataContent' was not declared in this scope
  129 |   setShowDataContent(true);
      |   ^~~~~~~~~~~~~~~~~~
```

**Comment by knl-le** [comment]
@AntumDeluge Sorry, forget to update convert.h

**Review by AntumDeluge — APPROVED** [review]

**Pull request merged**
